name: ktlint

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/*.kt"

jobs:
  ktlint:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint &&
          chmod a+x ktlint

      - name: Run ktlint
        run: |
          ./ktlint --android --reporter=plain,output=ktlint-report.txt --reporter=checkstyle,output=ktlint-checkstyle-report.xml

      - name: Upload ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: ktlint-report.txt